In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
data = pd.read_csv('insurance_data.csv')
data

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [4]:
type(data['age'])

pandas.core.series.Series

In [5]:
type(data[['age']])

pandas.core.frame.DataFrame

In [11]:
x = data.iloc[:,:-1]
x

age
0    22
1    25
2    47
3    52
4    46
5    56
6    55
7    60
8    62
9    61
10   18
11   28
12   27
13   29
14   49
15   55
16   25
17   58
18   19
19   18
20   21
21   26
22   40
23   45
24   50
25   54
26   23

In [12]:
y = y = data.iloc[:,-1]
y

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    0
11    0
12    0
13    0
14    1
15    1
16    1
17    1
18    0
19    0
20    0
21    0
22    1
23    1
24    1
25    1
26    0
Name: bought_insurance, dtype: int64

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [14]:
model = LogisticRegression()

In [15]:
model.fit(x_train,y_train)

LogisticRegression()

In [16]:
y_pred = model.predict(x_test)

In [17]:
x_test

age
17   58
14   49
18   19
3    52
23   45
10   18

In [18]:
y_pred

array([1, 1, 0, 1, 1, 0], dtype=int64)

In [19]:
y_test

17    1
14    1
18    0
3     0
23    1
10    0
Name: bought_insurance, dtype: int64

In [23]:
model.score(x_test,y_test)#in the case of accuracy score code will be accuracy.score(y_pred,y_test)

0.8333333333333334

In [21]:
model.predict_proba(x_test)

array([[0.04795632, 0.95204368],
       [0.15805894, 0.84194106],
       [0.93776133, 0.06223867],
       [0.10800643, 0.89199357],
       [0.25198743, 0.74801257],
       [0.94576637, 0.05423363]])

In [24]:
model.predict([[52]])#choosing random values and predicting

array([1], dtype=int64)

In [25]:
model.predict([[22]])

array([0], dtype=int64)